### PR TITLE
Add CLI flags for custom update lengths

### LINKED ISSUE #10: Cannot override update speeds with runtime flags
There are no runtime flags that allow a user to force the use of the predefined update speeds, or to define arbitrary ones.

### PR DESCRIPTION
**Pull request by esfalsa**
This PR adds support for the `-maj` and `-min` CLI flags to specify custom lengths. This exposes the same functionality as is currently available in interactive mode.

### CODE REVIEW

**Comment by AavHRF** [comment]
I'm not quite confident that we want to add those flags back. If I recall correctly, we specifically *removed* the `-maj` flag in the 2.0 release due to a change in how we handled time calculations. `-min` makes sense though.

**Comment by esfalsa** [comment]
Hmm, do you remember what exactly the issue was? The `-maj` flag as I've implemented it should function the same as the existing functionality for manually specifying an update length, so I figured it would work the same way with respect to time calculations, but I can check the code again.

**Comment by AavHRF** [comment]
> Hmm, do you remember what exactly the issue was? The `-maj` flag as I've implemented it should function the same as the existing functionality for manually specifying an update length, so I figured it would work the same way with respect to time calculations, but I can check the code again.

I don't remember, unfortunately. Upon testing, however, there seems to be no issue so perhaps I'm confusing this with a change I made in the beta branch. As long as nobody else on the development team is opposed to this change I will merge it into master.

**Review by AavHRF — APPROVED** [review]

**Comment by khronion** [comment]
Changes merged. Thank you @esfalsa!

**Pull request merged**
